image: docker:latest

variables:
  IMG_NAME: "jitesoft/composer"

after_script:
  - docker logout

php 7.2:
  stage: deploy
  variables:
    DOCKER_FILE: "7.2/Dockerfile"
  before_script:
    - docker login -u $HUB_USER -p $HUB_PW
    - docker pull jitesoft/php-fpm:7.2
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - PHP_V=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "PHP_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - PHP_SHORT="${PHP_V:0:3}"
    - echo "Building for php v ${PHP_V}. The image build hash is ${BUILD}"
    - TAGS="${PHP_SHORT} 7 stable latest"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master

php 7.1:
  stage: deploy
  variables:
    DOCKER_FILE: "7.1/Dockerfile"
  before_script:
    - docker login -u $HUB_USER -p $HUB_PW
    - docker pull jitesoft/php-fpm:7.1
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - PHP_V=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "PHP_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - PHP_SHORT="${PHP_V:0:3}"
    - echo "Building for php v ${PHP_V}. The image build hash is ${BUILD}"
    - TAGS="${PHP_SHORT}"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master

php 7.0:
  stage: deploy
  variables:
    DOCKER_FILE: "7.0/Dockerfile"
  before_script:
    - docker login -u $HUB_USER -p $HUB_PW
    - docker pull jitesoft/php-fpm:7.0
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - PHP_V=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "PHP_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - PHP_SHORT="${PHP_V:0:3}"
    - echo "Building for php v ${PHP_V}. The image build hash is ${BUILD}"
    - docker login -u $HUB_USER -p $HUB_PW
    - TAGS="${PHP_SHORT}"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
    - docker logout
  only:
    - master

php 5.6:
  stage: deploy
  variables:
    DOCKER_FILE: "5.6/Dockerfile"
  before_script:
    - docker login -u $HUB_USER -p $HUB_PW
    - docker pull jitesoft/php-fpm:5.6
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - PHP_V=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "PHP_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - PHP_SHORT="${PHP_V:0:3}"
    - echo "Building for php v ${PHP_V}. The image build hash is ${BUILD}"
    - TAGS="${PHP_SHORT} 5"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master
