stages:
  - deploy
  - notify

.build: &build
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - docker pull jitesoft/php-fpm:${VERSION}
  script:
    - docker build --build-arg VERSION=${VERSION} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --no-cache -q .
    - for tag in $TAGS; do docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/composer:${tag}; docker push jitesoft/composer:${tag}; done
  after_script:
    - docker run --rm jitesoft/composer:${VERSION} composer -V
    - docker run --rm jitesoft/composer:${VERSION} php -v

build:php:7.3:
  <<: *build
  variables:
    VERSION: "7.3"
    TAGS: "stable latest 7 ${VERSION}"

Build:php:7.2:
  variables:
    VERSION: "7.2"
    TAGS: "${VERSION}"
  <<: *build

Build:php:7.1:
  variables:
    VERSION: "7.1"
    TAGS: "${VERSION}"
  <<: *build

Build:php:7.0:
  variables:
    VERSION: "7.0"
    TAGS: "${VERSION}"
  <<: *build

Build:php:5.6:
  variables:
    VERSION: "5.6"
    TAGS: "${VERSION} 5"
  <<: *build

trigger_build:
  image: alpine:latest
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${NOTIFY_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4113741/trigger/pipeline"
