include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml

stages:
  - download
  - deploy
  - scan
  - notify

variables:
  PLATFORMS: "linux/amd64,linux/arm64"

download:
  stage: download
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache coreutils curl
  script:
    - mkdir downloads
    - cd downloads
    - curl -LOsS https://composer.github.io/installer.sha384sum
    - curl -L -o composer-setup.php https://getcomposer.org/installer
    - sha384sum --check installer.sha384sum
  artifacts:
    expire_in: 2 days
    paths:
      - downloads/

.build: &build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  stage: deploy
  dependencies:
    - download
  script:
    - C_VERSION=$(wget -qO- https://getcomposer.org | grep -oP "(?<=<strong>)([0-9]{0,3}(\.?)){3}" | awk 'NR==1{print $1}')
    - TAG_LIST=$(helper "jitesoft/composer,${CI_REGISTRY_IMAGE}" "${TAGS}")
    - docker buildx build --platform ${PLATFORMS} --progress plain --push ${TAG_LIST} ${HUB_LIST} --build-arg PHP_VERSION=${VERSION} --build-arg COMPOSER_VERSION=${C_VERSION} --build-arg BASE_IMAGE=${BASE_IMAGE} .
  tags: [ jitesoft, buildx, protected ]

build:php:7.4:
  <<: *build
  variables:
    VERSION: "7.4"
    TAGS: "stable,latest,7,7.4"
    BASE_IMAGE: "registry.gitlab.com/jitesoft/dockerfiles/php/cli"

build:php:7.3:
  <<: *build
  variables:
    VERSION: "7.3"
    TAGS: "7.3"
    BASE_IMAGE: "registry.gitlab.com/jitesoft/dockerfiles/php/cli"

scan:7.4:
  needs:
    - build:php:7.4
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:7.4

scan:7.3:
  needs:
    - build:php:7.3
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:7.3

# Trigger next pipeline (phpunit).
trigger_build:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${NOTIFY_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4113741/trigger/pipeline"
