include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
  - download
  - deploy
  - scan
  - notify

download:
  stage: download
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache coreutils curl
  script:
    - mkdir downloads
    - cd downloads
    - curl -LOsS https://composer.github.io/installer.sha384sum
    - curl -L -o composer-setup.php https://getcomposer.org/installer
    - sha384sum --check installer.sha384sum
  artifacts:
    expire_in: 2 days
    paths:
      - downloads/

.build: &build
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  stage: deploy
  dependencies:
    - download
  before_script:
    - apk add --no-cache grep
  script:
    - C_VERSION=$(wget -qO- https://getcomposer.org | grep -oP "(?<=Latest:\ v)(([0-9]{0,3}(\.?)){3})" | awk 'NR==1{print $1}')
    - docker build --build-arg BASE_IMAGE="${BASE_IMAGE}" --build-arg PHP_VERSION="${VERSION}" --label "com.jitesoft.app.composer.version=${C_VERSION}" -t ${IMAGE_NAME}:${VERSION}-tmp --no-cache .
    - |
      for tag in $TAGS; do
        docker tag ${IMAGE_NAME}:${VERSION}-tmp ${IMAGE_NAME}:${tag}
        docker tag ${IMAGE_NAME}:${VERSION}-tmp jitesoft/composer:${tag}${TAG_SUFFIX}
        docker tag ${IMAGE_NAME}:${VERSION}-tmp quay.io/jitesoft/composer:${tag}${QUAY_TAG_SUFFIX}
        docker push jitesoft/composer:${tag}${TAG_SUFFIX}
        docker push ${IMAGE_NAME}:${tag}
        docker push quay.io/jitesoft/composer:${tag}${QUAY_TAG_SUFFIX}
      done

build:php:7.3:
  <<: *build
  variables:
    VERSION: "7.3"
    TAGS: "stable latest 7 7.3"
    BASE_IMAGE: "registry.gitlab.com/jitesoft/dockerfiles/php/cli"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/cli"
    TAG_SUFFIX: "-cli"
    QUAY_TAG_SUFFIX: ""

build:php:7.2:
  <<: *build
  variables:
    VERSION: "7.2"
    TAGS: "7.2"
    BASE_IMAGE: "registry.gitlab.com/jitesoft/dockerfiles/php/cli"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/cli"
    TAG_SUFFIX: "-cli"
    QUAY_TAG_SUFFIX: ""


build:php:7.3:fpm:
  <<: *build
  variables:
    VERSION: "7.3"
    TAGS: "stable latest 7 7.3"
    BASE_IMAGE: "registry.gitlab.com/jitesoft/dockerfiles/php/fpm"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fpm"
    TAG_SUFFIX: ""
    QUAY_TAG_SUFFIX: "-fpm"

build:php:7.2:fpm:
  <<: *build
  variables:
    VERSION: "7.2"
    TAGS: "7.2"
    BASE_IMAGE: "registry.gitlab.com/jitesoft/dockerfiles/php/fpm"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fpm"
    TAG_SUFFIX: ""
    QUAY_TAG_SUFFIX: "-fpm"

# Container scanning!
scan:7.3:fpm:
  needs:
    - build:php:7.3:fpm
  stage: scan
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/fpm:7.3

scan:7.2:fpm:
  needs:
    - build:php:7.2:fpm
  stage: scan
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/fpm:7.2

scan:7.3:cli:
  needs:
    - build:php:7.3
  stage: scan
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/cli:7.3

scan:7.2:cli:
  needs:
    - build:php:7.2
  stage: scan
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/cli:7.2

# Trigger next pipeline (phpunit).
trigger_build:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${NOTIFY_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4113741/trigger/pipeline"
